CREATE DATABASE CloudTowerDB;

USE CloudTowerDB;

CREATE TABLE Entidad(
    idEntidad INT NOT NULL PRIMARY KEY,
    NOM NVARCHAR(40) NOT NULL,
    TEL CHAR(10) NOT NULL UNIQUE,
    CORREO NVARCHAR(320) NOT NULL UNIQUE,
    DIR NVARCHAR(50) NOT NULL

);

